export const FETCH_CHARACTERS = 'FETCH_CHARACTERS';
export const FETCH_CHARACTERS_SUCCESS = 'FETCH_CHARACTERS_SUCCESS';
export const FETCH_CHARACTERS_FAIL = 'FETCH_CHARACTERS_FAIL';

export const FETCH_CHARACTER = 'FETCH_CHARACTER';
export const FETCH_CHARACTER_SUCCESS = 'FETCH_CHARACTER_SUCCESS';
export const FETCH_CHARACTER_FAIL = 'FETCH_CHARACTER_FAIL';

export const SET_CURRENT_CHARACTER = 'SET_CURRENT_CHARACTER';
export const UNSET_CURRENT_CHARACTER = 'UNSET_CURRENT_CHARACTER';
